/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gpao_V_1_0;

import static java.lang.Thread.sleep;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static java.lang.Thread.sleep;

/**
 *
 * @author Assane Adirou
 */
public class Menu_Gpao extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Gpao
     */
    public Menu_Gpao() {
        initComponents();
        datecourante();
    }
    
    // methode pour la recuperation  de la date et l'heure courante
    public void datecourante() {
        Thread clock = new Thread() {
            public void run() {
                for (;;) {
                    Calendar Cal = new GregorianCalendar();

                    int sconde = Cal.get(Calendar.SECOND);
                    int minute = Cal.get(Calendar.MINUTE);
                    int heure = Cal.get(Calendar.HOUR);
                    int AM_PM = Cal.get(Calendar.AM_PM);  
                    String pa;
                    if(AM_PM==1){
                        pa="PM";
                    }else{
                        pa="AM";
                    }
                    
                         
                    lab_heure.setText( + heure + ":" + (minute) + ":" + sconde +" "+pa  );
                    
                 int mois = Cal.get(Calendar.MONTH);
                    int annee = Cal.get(Calendar.YEAR);
                    int jour = Cal.get(Calendar.DAY_OF_MONTH);

                    lab_date.setText( + jour + "/" + (mois+1) + "/" + annee);              
                    
                    
                    try {
                        sleep(1000);

                    } catch (InterruptedException ex) {
                        Logger.getLogger(Calendar.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            }

        };
        
clock.start();
    }
// methose pour quitter
    public void fermer(){
    
    this.dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lab_date = new javax.swing.JLabel();
        lab_heure = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_Article = new javax.swing.JButton();
        btn_Lien = new javax.swing.JButton();
        Btn_Remplacement = new javax.swing.JButton();
        Btn_Poste_Charge = new javax.swing.JButton();
        Btn_Operation = new javax.swing.JButton();
        Btn_Mvt_Stock = new javax.swing.JButton();
        Btn_Mvt_Stock1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu De Gestion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 2, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gpao Version 1.0");

        lab_date.setBackground(new java.awt.Color(102, 102, 102));
        lab_date.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lab_date.setForeground(new java.awt.Color(255, 255, 255));
        lab_date.setText("01/12/2011");

        lab_heure.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lab_heure.setForeground(new java.awt.Color(255, 255, 255));
        lab_heure.setText("02:27:40 AM");

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Accueil", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 2, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        btn_Article.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        btn_Article.setText("Article");
        btn_Article.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ArticleActionPerformed(evt);
            }
        });

        btn_Lien.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        btn_Lien.setText("Lien De Nomenclature");
        btn_Lien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LienActionPerformed(evt);
            }
        });

        Btn_Remplacement.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        Btn_Remplacement.setText("Remplacement");
        Btn_Remplacement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_RemplacementActionPerformed(evt);
            }
        });

        Btn_Poste_Charge.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        Btn_Poste_Charge.setText("Poste de Charge");
        Btn_Poste_Charge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Poste_ChargeActionPerformed(evt);
            }
        });

        Btn_Operation.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        Btn_Operation.setText("Operation");
        Btn_Operation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_OperationActionPerformed(evt);
            }
        });

        Btn_Mvt_Stock.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        Btn_Mvt_Stock.setText("Mouvement De Stock");
        Btn_Mvt_Stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Mvt_StockActionPerformed(evt);
            }
        });

        Btn_Mvt_Stock1.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        Btn_Mvt_Stock1.setText("Deconnexion");
        Btn_Mvt_Stock1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Mvt_Stock1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jButton2.setText("Gestion Utilisateur");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_Lien, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addComponent(btn_Article, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Btn_Remplacement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Btn_Poste_Charge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Btn_Operation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Btn_Mvt_Stock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Btn_Mvt_Stock1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Article)
                .addGap(18, 18, 18)
                .addComponent(btn_Lien)
                .addGap(18, 18, 18)
                .addComponent(Btn_Remplacement)
                .addGap(18, 18, 18)
                .addComponent(Btn_Poste_Charge)
                .addGap(18, 18, 18)
                .addComponent(Btn_Operation)
                .addGap(18, 18, 18)
                .addComponent(Btn_Mvt_Stock)
                .addGap(28, 28, 28)
                .addComponent(jButton2)
                .addGap(26, 26, 26)
                .addComponent(Btn_Mvt_Stock1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 668, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lab_date)
                        .addGap(18, 18, 18)
                        .addComponent(lab_heure, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_heure, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab_date))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_LienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LienActionPerformed
      // instanciation de la classe lien de nomenclature
        Lien_Nomenclature ln = new Lien_Nomenclature();
       ln.setVisible(rootPaneCheckingEnabled);
       this.dispose();
    }//GEN-LAST:event_btn_LienActionPerformed

    private void Btn_RemplacementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_RemplacementActionPerformed
             // instanciation de la classe remplacement
        try {
            Remplacement rr = new Remplacement();
            rr.setVisible(rootPaneCheckingEnabled);
            this.dispose();
        } catch (SQLException ex) {
          
        }
    }//GEN-LAST:event_Btn_RemplacementActionPerformed

    private void Btn_Poste_ChargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Poste_ChargeActionPerformed
           // instanciation de la classe poste de charge
        Poste_d_charge pc = new Poste_d_charge();
      pc.setVisible(rootPaneCheckingEnabled);
      this.dispose();
    }//GEN-LAST:event_Btn_Poste_ChargeActionPerformed

    private void Btn_OperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_OperationActionPerformed
        try {
               // instanciation de la classe operation
            Operation op = new  Operation();
            op.setVisible(rootPaneCheckingEnabled);
            this.dispose();
        } catch (SQLException ex) {
            
        }
    }//GEN-LAST:event_Btn_OperationActionPerformed

    private void Btn_Mvt_StockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Mvt_StockActionPerformed
             // instanciation de la classe mouvement de stock
        Mouvement_De_Stock mvst = new Mouvement_De_Stock();
        mvst.setVisible(rootPaneCheckingEnabled);
        this.dispose();
    }//GEN-LAST:event_Btn_Mvt_StockActionPerformed

    private void btn_ArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ArticleActionPerformed
     // instanciation de la classe gestion d'article
        Gestion_Article ga = new Gestion_Article();
        ga.setVisible(rootPaneCheckingEnabled);
        this.dispose();
        
    }//GEN-LAST:event_btn_ArticleActionPerformed

    private void Btn_Mvt_Stock1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Mvt_Stock1ActionPerformed
             // fermeture de la page
        JOptionPane.showMessageDialog(null,"Fermeture imminente de l'Application Aurevoir !!!");
        System.exit(0);
        
    }//GEN-LAST:event_Btn_Mvt_Stock1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
   Gestion_Utilisateur gu=new Gestion_Utilisateur();
   gu.setVisible(rootPaneCheckingEnabled);
   this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Gpao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Gpao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Gpao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Gpao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Gpao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Mvt_Stock;
    private javax.swing.JButton Btn_Mvt_Stock1;
    private javax.swing.JButton Btn_Operation;
    private javax.swing.JButton Btn_Poste_Charge;
    private javax.swing.JButton Btn_Remplacement;
    private javax.swing.JButton btn_Article;
    private javax.swing.JButton btn_Lien;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lab_date;
    private javax.swing.JLabel lab_heure;
    // End of variables declaration//GEN-END:variables
}
